before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/mmds
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - linux
      - solaris
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
    flags:
      - -trimpath
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - maintainer: &author Maxime VISONNEAU <maxime.visonneau@gmail.com>
    description: &description Missed (AWS) Meta-Data (service)
    license: &license Apache 2.0
    homepage: &homepage https://github.com/mvisonneau/mmds
    vendor: *author
    file_name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}'
    formats:
      - deb
      - rpm

brews:
  - description: *description
    homepage: *homepage
    folder: Formula
    tap:
      owner: mvisonneau
      name: homebrew-tap

scoop:
  description: *description
  homepage: *homepage
  license: *license
  bucket:
    owner: mvisonneau
    name: scoops

checksum:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_sha512sums.txt'
  algorithm: sha512

signs:
  - artifacts: checksum
    args:
      [
        '-u',
        'C09CA9F71C5C988E65E3E5FCADEA38EDC46F25BE',
        '--output',
        '${signature}',
        '--detach-sign',
        '${artifact}',
      ]

changelog:
  skip: true