---
version: 2

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/mmds
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - linux
      - solaris
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
    flags:
      - -trimpath
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - name_template: '{{ .ProjectName }}_edge_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

release:
  disable: true

signs:
  - artifacts: checksum
    args:
      [
        '-u',
        'C09CA9F71C5C988E65E3E5FCADEA38EDC46F25BE',
        '--output',
        '${signature}',
        '--detach-sign',
        '${artifact}',
      ]

checksum:
  name_template: '{{ .ProjectName }}_edge_sha512sums.txt'
  algorithm: sha512

changelog:
  disable: true
